[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"  # 用于计算哈希
serde = { version = "1.0", features = ["derive"] }  # 启用 derive 特性
serde_json = "1.0"  # 可选，用于序列化和反序列化